version: "3.9"

services:
  mysql:
    platform: linux/amd64
    build: ./mysql/
    image: compose-test
    container_name: bulletin-board-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bulletin-board
    volumes:
      - ./mysql/DB:/docker-entrypoint-initdb.d
