version: "3.9"

services:
  mysql:
    container_name: test
    image: mysql
    platform: linux/arm64/v8
    ports:
      - ${DB_PORT}:3306
    restart: always
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./stored:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}